/* Accessible DOM inventory, mouse/keyboard/touch input, import/export and menus. */
(function(V){'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function icon(id){const t=V.items[id];if(!t)return'';const c=t.color;let shape;
 if(t.block)shape=`<path fill="${c}" d="M16 2 30 9 16 17 2 9Z"/><path fill="${c}" d="M2 9 16 17 16 33 2 25Z"/><path fill="#0002" d="M2 9 16 17 16 33 2 25Z"/><path fill="${c}" d="M16 17 30 9 30 25 16 33Z"/><path fill="#0004" d="M16 17 30 9 30 25 16 33Z"/><path fill="#ffffff25" d="M16 2 30 9 16 17 2 9Z"/>`;
 else if(t.tool){shape=`<path fill="#9a7649" d="m9 30-4-4L23 8l4 4Z"/>`;shape+=t.tool==='sword'?`<path fill="${c}" d="m12 18 13-15 5-1-1 6-13 15Z"/><path fill="#deba73" d="m9 14 11 11-3 3L6 17Z"/>`:t.tool==='shovel'?`<path fill="${c}" d="m20 5 8 1 3 8-7 7-10-9Z"/>`:t.tool==='axe'?`<path fill="${c}" d="M10 4h15l5 9-6 8-11-8Z"/>`:t.tool==='hoe'?`<path fill="${c}" d="m7 6 15-3 8 9-4 4-9-7-9 2Z"/>`:`<path fill="${c}" d="m4 8 8-6 12 2 7 9-2 8-5-10-11-4-8 5Z"/>`;}
 else if(t.food){shape=id===107?`<path fill="#6e9b51" d="m15 11 1-9 8 3-8 5Z"/><path fill="${c}" d="M4 13 10 8l6 3 7-3 6 6-3 14-7 4-4-2-5 1-7-8Z"/>`:`<path fill="${c}" d="m4 16 7-9 15 1 5 10-4 10-17 2-7-7Z"/><path fill="#ffe7a64d" d="m9 15 3-4 10 1 3 5-3 3-11-1Z"/>`;}
 else if(id===117)shape=`<path fill="${c}" d="M8 5 13 3l3 5 4-5 6 2 6 8-5 6-3-3v16H8V16l-4 3-4-6Z"/><path fill="#ffffff35" d="M11 12h10v16H11Z"/>`;
 else if([114,115,116].includes(id))shape=`<path fill="${c}" d="M3 10h27l-4 21H7Z"/><path fill="none" stroke="#dbe5db" stroke-width="3" d="M7 11V6q10-9 19 0v6"/><path fill="#0003" d="M7 13h20l-2 7H9Z"/>`;
 else shape=`<path fill="${c}" d="M16 3 29 11 25 27 12 33 3 21 5 10Z"/><path fill="#ffffff38" d="M16 3 23 11 12 18 5 10Z"/><path fill="#0002" d="m12 18 13 9-13 6-9-12Z"/>`;
 return`<svg class="icon" viewBox="0 0 32 36" aria-hidden="true">${shape}</svg>`;
}
class UI{
 constructor(g){this.g=g;g.ui=this;this.search='';this.tab='craft';this.lastHUD=0;this.lastFurnace=0;this.stationKey=null;this.bind();$('seedInput').value=g.world.seed;$('modeSelect').value=g.mode;this.refresh();if(g.pendingNotice)this.toast(g.pendingNotice);}
 toast(s){$('toast').textContent=s;$('toast').style.opacity=1;clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>$('toast').style.opacity=0,3300);}
 requestLock(){if(matchMedia('(pointer:coarse)').matches)return;try{const p=this.g.canvas.requestPointerLock();p?.catch(()=>this.toast('Mouse capture unavailable. Drag on the world to look around.'));}catch{}}
 launch(){const g=this.g,seed=$('seedInput').value.trim()||'wild-2',mode=$('modeSelect').value;if(seed!==g.world.seed||mode!==g.mode){g.save();g.newWorld(seed,mode,true);}if(g.dead){this.showDeath('your previous adventure');return;}g.started=true;g.paused=false;g.keys={};this.closeMenu();this.refresh();this.requestLock();g.save();}
 menu(){const g=this.g;this.closePanel(false);g.paused=true;g.mousedown=false;g.keys={};document.exitPointerLock?.();$('menu').classList.remove('hidden');$('hud').classList.add('hidden');$('launch').textContent=g.started?'Resume your world →':'Enter your world →';$('seedInput').value=g.world.seed;$('modeSelect').value=g.mode;g.save();}
 closeMenu(){$('menu').classList.add('hidden');$('hud').classList.remove('hidden');$('death').classList.add('hidden');}
 showDeath(cause){this.closePanel(false);this.g.cursor=null;$('menu').classList.add('hidden');$('inventoryModal').classList.add('hidden');$('death').classList.remove('hidden');$('deathReason').textContent='Your journey ended because of '+cause+'.';document.exitPointerLock?.();}
 openPanel(kind='inventory',key=null){const g=this.g;if(g.paused||g.dead||!g.started)return;g.panel=kind;g.mousedown=false;g.keys={};this.stationKey=key;this.tab='craft';this.search='';document.exitPointerLock?.();$('inventoryModal').classList.remove('hidden');this.refreshPanel();}
 closePanel(lock=true){const g=this.g;if(!g.panel)return;g.panel=null;if(g.cursor){const s=g.cursor,left=g.inventory.add(s.id,s.count,s.dur);if(left)g.drop(s.id,left,g.player.x,g.player.y+.3,g.player.z,s.dur);g.cursor=null;}$('inventoryModal').classList.add('hidden');g.mousedown=false;this.refresh();g.save();if(lock&&!g.dead)this.requestLock();}
 slot(s,index,collection='inventory',hotbar=false){const t=V.items[s?.id];return`<button type="button" class="slot${hotbar&&this.g.selected===index?' active':''}" data-slot="${index}" data-collection="${collection}" title="${t?esc(t.name+' × '+s.count+(s.dur?' · Durability '+s.dur:'')):'Empty slot'}" aria-label="${t?esc(t.name+' '+s.count):'Empty slot'}">${hotbar||collection==='inventory'&&index<9?`<span class="num">${index+1}</span>`:''}${t?icon(s.id):''}${s&&s.count>1?`<span class="count">${s.count}</span>`:''}${s?.dur?`<span class="dur"><i style="width:${Math.max(0,s.dur/t.durability*100)}%"></i></span>`:''}</button>`;}
 refresh(){const g=this.g;$('hotbar').innerHTML=g.inventory.slots.slice(0,9).map((s,i)=>this.slot(s,i,'hotbar',true)).join('');for(const b of $('hotbar').querySelectorAll('button'))b.onclick=()=>{g.selected=+b.dataset.slot;this.refresh();};$('heldName').textContent=V.items[g.held()?.id]?.name||'Empty hands';$('vitals').classList.toggle('hidden',g.mode==='creative');$('flyTouch').classList.toggle('hidden',g.mode!=='creative');$('downTouch').classList.toggle('hidden',g.mode!=='creative');if(g.panel)this.refreshPanel();}
 refreshPanel(){const g=this.g;if(!g.panel)return;const kind=g.panel,titles={inventory:'Inventory & crafting',bench:'Workbench',chest:'Chest storage',furnace:'Furnace'};$('panelTitle').textContent=titles[kind]||'Inventory';$('panelEyebrow').textContent=kind==='inventory'?'Your backpack':`Station · ${this.stationKey}`;
 const slots=g.inventory.slots;
 let left=`<h3 class="sectionTitle">Hotbar</h3><div class="grid">${slots.slice(0,9).map((s,i)=>this.slot(s,i)).join('')}</div><h3 class="sectionTitle bag">Backpack</h3><div class="grid">${slots.slice(9).map((s,i)=>this.slot(s,i+9)).join('')}</div><div class="panelHelp">Click to pick up / move a stack. Right-click to split or place one.<br>Move tools into slots 1–9 to equip them. Shift-click transfers chest stacks.</div><div class="carry">${g.cursor?icon(g.cursor.id)+`<span>Carrying ${esc(V.items[g.cursor.id].name)} × ${g.cursor.count}<br><small>Click a slot to put it down.</small></span>`:'No stack selected. Close the bag to return to the world.'}</div>`;
 let right='';const e=g.world.entities[this.stationKey];
 if(kind==='chest'){right=`<h3 class="sectionTitle">Chest · 27 slots</h3><div class="grid">${(e?.slots||Array(27).fill(null)).map((s,i)=>this.slot(s,i,'chest')).join('')}</div><p class="panelHelp">Stored items persist with this world. Break the chest to drop its contents.</p>`;}
 else if(kind==='furnace'){right=`<h3 class="sectionTitle">Smelting</h3><div class="stationSlots"><div>${this.slot(e?.input,0,'input')}<label>Input</label></div><div>${this.slot(e?.fuel,0,'fuel')}<label>Fuel</label></div><div style="font-size:22px;color:var(--gold)">→</div><div>${this.slot(e?.output,0,'output')}<label>Output</label></div></div><div class="progress"><i style="width:${(e?.progress||0)/6*100}%"></i></div><p class="panelHelp">${e?.burn>0?'Burning · '+Math.ceil(e.burn)+' seconds of fuel remain.':'Add raw ore, sand, meat, logs or clay. Then add coal, logs or planks as fuel.'}<br>One item takes six seconds. Fuel and work in progress are saved.</p><div class="guide"><p>Iron ore → iron ingots<br>Gold ore → gold ingots<br>Sand → glass · Raw meat → cooked meat<br>Logs → charcoal (coal item) · Clay → bricks</p></div>`;}
 else{right=`<div class="tabs"><button data-tab="craft" class="${this.tab==='craft'?'on':''}">Crafting</button>${g.mode==='creative'?`<button data-tab="catalog" class="${this.tab==='catalog'?'on':''}">All items</button>`:''}<button data-tab="guide" class="${this.tab==='guide'?'on':''}">Field guide</button></div><div id="craftContent"></div>`;}
 $('panelMain').innerHTML=`<div>${left}</div><div>${right}</div>`;
 for(const b of $('panelMain').querySelectorAll('[data-slot]')){b.onclick=e=>this.swap(b.dataset.collection,+b.dataset.slot,false,e.shiftKey);b.oncontextmenu=e=>{e.preventDefault();this.swap(b.dataset.collection,+b.dataset.slot,true,false);};}
 for(const b of $('panelMain').querySelectorAll('[data-tab]'))b.onclick=()=>{this.tab=b.dataset.tab;this.refreshPanel();};
 if(kind==='inventory'||kind==='bench')this.renderCraftContent();
 }
 renderCraftContent(){const g=this.g,c=$('craftContent');if(!c)return;
 if(this.tab==='guide'){c.innerHTML=`<div class="guide"><h3>Your first night</h3><p><b>1.</b> Hold Mine on an oak log. Open your bag with E. Make planks, sticks, then a workbench.</p><p><b>2.</b> Put the workbench in your hotbar. Place it with Use, then Use it again to open its recipes. Make a wood pickaxe.</p><p><b>3.</b> Mine stone for cobblestone. Make stone tools and a furnace. Mine coal and iron. Smelt raw iron with fuel.</p><p><b>4.</b> Apples can drop from leaves. Animals drop meat; sheep also drop wool. Cook meat for more nourishment.</p><p><b>5.</b> Build a shelter. Craft torches and a bed. Use a bed at night to sleep and set your spawn.</p><p><b>6.</b> Hoe earth, plant seeds, and irrigate with water within four blocks. Wheat makes bread.</p><p class="muted">Creative: E → All items for blocks and tools. F toggles flight; Space / Q go up / down. Full modern Minecraft parity, multiplayer and additional dimensions are not implemented.</p></div>`;return;}
 c.innerHTML=`<input id="recipeSearch" type="search" placeholder="${this.tab==='catalog'?'Find an item…':'Find a recipe…'}" aria-label="Search recipes or items" value="${esc(this.search)}"><div id="recipeList"></div>`;$('recipeSearch').oninput=e=>{this.search=e.target.value;this.renderRecipes();};this.renderRecipes();
 }
 renderRecipes(){const g=this.g,list=$('recipeList');if(!list)return;const search=this.search.toLowerCase();
 if(this.tab==='catalog'){list.className='catalogWrap';list.innerHTML=`<div class="catalog">${Object.values(V.items).filter(i=>![12,26,28].includes(i.id)&&i.name.toLowerCase().includes(search)).map(i=>`<button class="slot" data-give="${i.id}" title="${esc(i.name)}" aria-label="Get ${esc(i.name)}">${icon(i.id)}</button>`).join('')}</div>`;for(const b of list.querySelectorAll('[data-give]'))b.onclick=()=>{const id=+b.dataset.give;if(g.inventory.add(id,V.items[id].stack))this.toast('Your inventory is full. Move or drop a stack first.');this.refresh();};return;}
 list.className='recipes';list.innerHTML=V.recipes.map((r,index)=>{if(!r.name.toLowerCase().includes(search))return'';const stationOK=r.station==='hand'||g.panel==='bench';const ready=stationOK&&Object.entries(r.cost).every(([id,n])=>g.inventory.count(id)>=n);const costs=Object.entries(r.cost).map(([id,n])=>`${V.items[id].name} ${g.inventory.count(id)}/${n}`).join(' · ');return`<button class="recipe" data-recipe="${index}" ${!ready?'disabled':''}>${icon(r.out)}<span><strong>${esc(r.name)}${r.n>1?' × '+r.n:''}</strong><small class="${!ready?'needs':''}">${esc(costs)}${!stationOK?'<br>Requires a placed workbench.':''}</small></span></button>`;}).join('')||'<p class="panelHelp">No matching recipes.</p>';
 for(const b of list.querySelectorAll('[data-recipe]'))b.onclick=()=>{const r=V.recipes[+b.dataset.recipe];if(g.inventory.craft(r,g.panel==='bench'?'bench':'hand')){g.sound('craft');this.toast('Crafted '+r.n+' '+V.items[r.out].name);this.refresh();}else this.toast('Not enough materials, space, or the required station.');};
 }
 swap(collection,index,right,shift){const g=this.g,e=g.world.entities[this.stationKey];let arr,prop;
 if(collection==='inventory')arr=g.inventory.slots;else if(collection==='chest'){if(!e||e.kind!=='chest')return;arr=e.slots;}else{if(!e||e.kind!=='furnace')return;prop=collection;arr={[index]:e[prop]};}
 let s=arr[index],cur=g.cursor;
 if(shift&&!right&&s&&g.panel==='chest'&&!cur){if(collection==='inventory'){const chest=new V.Inventory(27,e.slots),left=chest.add(s.id,s.count,s.dur);e.slots=chest.slots;arr[index]=left?{...s,count:left}:null;}else{const left=g.inventory.add(s.id,s.count,s.dur);arr[index]=left?{...s,count:left}:null;}this.refresh();return;}
 if(prop==='output'){if(cur&&(!s||cur.id!==s.id||V.items[s.id].stack===1))return;if(s){const room=V.items[s.id].stack-(cur?.count||0),n=Math.min(right?1:s.count,room);if(n>0){g.cursor=cur?{...cur,count:cur.count+n}:{...s,count:n};s.count-=n;if(!s.count)s=null;e.output=s;}}this.refresh();return;}
 if(cur&&(prop==='fuel'&&!V.items[cur.id].fuel||prop==='input'&&!V.smelts[cur.id])){this.toast(prop==='fuel'?'That item is not furnace fuel.':'That item cannot be smelted.');return;}
 if(right){if(!cur&&s){const n=Math.ceil(s.count/2);g.cursor={...s,count:n};s.count-=n;if(!s.count)s=null;}else if(cur&&(!s||s.id===cur.id&&s.count<V.items[s.id].stack)){if(s)s.count++;else s={...cur,count:1};if(--cur.count<=0)g.cursor=null;}}
 else if(cur&&s&&cur.id===s.id&&V.items[s.id].stack>1){const n=Math.min(cur.count,V.items[s.id].stack-s.count);s.count+=n;cur.count-=n;if(!cur.count)g.cursor=null;}else{g.cursor=s;s=cur;}
 if(prop)e[prop]=s;else arr[index]=s;this.refresh();
 }
 hud(now){const g=this.g;$('mineFill').style.width=Math.min(100,g.mineProgress*100)+'%';$('mineTrack').style.opacity=g.mineProgress>0?1:0;if(now-this.lastHUD<150)return;this.lastHUD=now;
 const p=g.player,terrain=g.world.terrain(Math.floor(p.x),Math.floor(p.z));$('coordinates').textContent=`${terrain.biome.toUpperCase()} / ${Math.floor(p.x)}, ${Math.floor(p.y)}, ${Math.floor(p.z)}`;$('clock').textContent=`${g.mode==='creative'?'CREATIVE':'DAY '+(Math.floor(g.time/720)+1)} · ${g.daylight()<.4?'NIGHT':'DAYLIGHT'}${g.flying?' · FLYING':''}`;
 $('health').textContent='♥'.repeat(Math.ceil(g.health/2))+'♡'.repeat(10-Math.ceil(g.health/2));$('health').title=`Health ${Math.ceil(g.health)}/20`;$('hunger').textContent='◆'.repeat(Math.ceil(g.hunger/2))+'◇'.repeat(10-Math.ceil(g.hunger/2));$('hunger').title=`Hunger ${Math.ceil(g.hunger)}/20`;
 $('extraVitals').textContent=(g.breath<10?'AIR '+Math.ceil(g.breath)+' / 10   ':'')+(g.armor?'ARMOR '+Math.ceil(g.armor.dur/V.items[g.armor.id].durability*100)+'%   ':'')+(g.mode==='creative'?'UNLIMITED BUILDING · E FOR ALL ITEMS':'XP '+g.xp);
 const h=g.target,item=V.items[g.held()?.id],mining=h?V.mining(h.type,g.held()):null;$('target').textContent=h?V.blocks[h.type].name+([19,20,21,24,25,26].includes(h.type)?' · Use to interact':mining&&!mining.drop&&V.blocks[h.type].tier?' · Needs a better pickaxe':''):'';
 const goals=[['wood','Hold Mine on an oak log.'],['bench','Craft planks and a workbench in your bag.'],['stone','Craft a wood pickaxe. Mine stone.'],['iron','Mine iron with a stone pick. Smelt it.'],['food','Find food. Cook a meal.'],['bed','Craft a bed. Build a safe place to rest.'],['farm','Hoe earth near water. Plant seeds.'],['diamond','Bring an iron pick into the deep caves.']];const goal=goals.find(([k])=>!g.achievements[k]);$('goalLabel').textContent=g.mode==='creative'?'Create without limits':goal?'Field notes':'Make this world yours';$('goal').textContent=g.mode==='creative'?'E: all items · F: fly · Space / Q: up / down':goal?goal[1]:'Explore. Build. Grow something worth returning to.';
 $('waterTint').style.display=g.world.get(Math.floor(p.x),Math.floor(p.y+1.6),Math.floor(p.z))===13?'block':'none';
 if(g.panel==='furnace'&&now-this.lastFurnace>450){this.lastFurnace=now;this.refreshPanel();}
 }
 bind(){const g=this.g,canvas=g.canvas;
 $('launch').onclick=()=>this.launch();$('pauseButton').onclick=()=>this.menu();$('bagButton').onclick=$('bagTouch').onclick=()=>this.openPanel();$('closeInventory').onclick=()=>this.closePanel();$('respawn').onclick=()=>{g.respawn();this.requestLock();};
 $('newSeedButton').onclick=()=>{$('seedInput').value='wild-'+Math.random().toString(36).slice(2,9);$('launch').textContent='Open new world →';};
 $('shareButton').onclick=async()=>{const url=new URL(location.href);url.search='';url.searchParams.set('seed',g.world.seed);url.searchParams.set('mode',g.mode);try{await navigator.clipboard.writeText(url.href);this.toast('Game link copied. The link shares terrain, not saved builds.');}catch{this.toast(url.href);}};
 $('exportButton').onclick=()=>{g.save();const blob=new Blob([JSON.stringify(g.snapshot())],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='voxel-wild-2-'+g.world.seed.replace(/[^a-z0-9_-]/gi,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);this.toast('World exported, including your inventory and builds.');};
 $('importButton').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>8*1024*1024)throw Error('World files must be under 8 MB.');const data=JSON.parse(await file.text());g.save();const targetKey='voxel-wild-v2:'+(data.mode==='creative'?'creative':'survival')+':'+data.world?.seed;if(localStorage.getItem(targetKey)&&!confirm('Replace saved progress for this seed? Export it first to keep a backup.'))return;g.restore(data);g.save();g.started=false;g.paused=true;g.mousedown=false;g.keys={};g.renderer.updateChunks(g.world,g.player,g.radius,60);$('seedInput').value=g.world.seed;$('modeSelect').value=g.mode;$('launch').textContent='Enter imported world →';this.refresh();this.toast('World imported. Other world seeds are unchanged.');}catch(err){this.toast('Import rejected: '+err.message);}e.target.value='';};
 window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)&&e.code!=='Escape')return;
 if(e.code==='Escape'){e.preventDefault();if(g.panel)this.closePanel();else if(!g.paused)this.menu();else if(g.started&&!g.dead)this.launch();return;}if(g.paused||g.dead)return;
 if(e.code==='KeyE'&&!e.repeat){e.preventDefault();if(g.panel)this.closePanel();else this.openPanel();return;}if(g.panel)return;
 if(e.code==='KeyF'&&!e.repeat&&g.mode==='creative'){g.flying=!g.flying;g.vy=0;this.toast(g.flying?'Flight enabled. Space rises; Q descends.':'Walking.');}
 if(e.code==='KeyQ'&&!e.repeat&&!g.flying){const s=g.held();if(s){g.drop(s.id,1,g.player.x+Math.sin(g.yaw)*1.8,g.player.y+1,g.player.z-Math.cos(g.yaw)*1.8,s.dur);s.count--;if(!s.count)g.inventory.slots[g.selected]=null;this.refresh();}}
 if(/^Digit[1-9]$/.test(e.code)){g.selected=+e.code.slice(-1)-1;this.refresh();}
 if(['Space','KeyW','KeyA','KeyS','KeyD','KeyQ','ShiftLeft','ShiftRight'].includes(e.code)){e.preventDefault();g.keys[e.code]=true;}});
 window.addEventListener('keyup',e=>delete g.keys[e.code]);window.addEventListener('blur',()=>{g.keys={};g.mousedown=false;if(g.started&&!g.paused&&!g.dead)this.menu();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&g.started){g.save();if(!g.dead)this.menu();}});window.addEventListener('beforeunload',()=>g.save());
 canvas.oncontextmenu=e=>e.preventDefault();canvas.addEventListener('mousedown',e=>{if(g.paused||g.panel||g.dead)return;if(e.button===0){g.mousedown=true;if(document.pointerLockElement!==canvas)this.requestLock();}if(e.button===2)g.use();});window.addEventListener('mouseup',()=>g.mousedown=false);
 window.addEventListener('mousemove',e=>{if(g.paused||g.panel||g.dead)return;if(document.pointerLockElement===canvas){g.yaw+=e.movementX*.0026;g.pitch=Math.max(-1.52,Math.min(1.52,g.pitch-e.movementY*.0026));}else if(e.buttons===1&&e.target===canvas){g.yaw+=e.movementX*.004;g.pitch=Math.max(-1.52,Math.min(1.52,g.pitch-e.movementY*.004));}});
 document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&!g.panel&&!g.paused&&g.started&&!g.dead&&!matchMedia('(pointer:coarse)').matches)this.menu();});
 canvas.addEventListener('wheel',e=>{if(g.paused||g.panel)return;e.preventDefault();g.selected=(g.selected+(e.deltaY>0?1:8))%9;this.refresh();},{passive:false});
 let look=null;canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'||g.paused||g.panel)return;look={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!look||look.id!==e.pointerId)return;g.yaw+=(e.clientX-look.x)*.004;g.pitch=Math.max(-1.52,Math.min(1.52,g.pitch-(e.clientY-look.y)*.004));look.x=e.clientX;look.y=e.clientY;});const stopLook=e=>{if(look?.id===e.pointerId)look=null;};canvas.addEventListener('pointerup',stopLook);canvas.addEventListener('pointercancel',stopLook);
 for(const b of document.querySelectorAll('[data-key]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);g.keys[b.dataset.key]=true;};const up=()=>delete g.keys[b.dataset.key];b.onpointerup=up;b.onpointercancel=up;b.onlostpointercapture=up;}
 $('mineTouch').onpointerdown=e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);g.mousedown=true;};for(const name of['onpointerup','onpointercancel','onlostpointercapture'])$('mineTouch')[name]=()=>g.mousedown=false;
 $('useTouch').onclick=()=>g.use();$('flyTouch').onclick=()=>{if(g.mode==='creative'){g.flying=!g.flying;g.vy=0;}};
 }
}
V.UI=UI;
try{const game=V.game=new V.Game($('game'));V.ui=new UI(game);window.__voxelReady=true;requestAnimationFrame(t=>game.loop(t));if(new URLSearchParams(location.search).get('autoplay')==='1'){game.started=true;game.paused=false;V.ui.closeMenu();}}
catch(e){$('fatal').textContent='Could not start Voxel Wild: '+e.message;$('fatal').classList.remove('hidden');$('launch').disabled=true;console.error(e);}
})(globalThis.VW);
