'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),V=require('./systems.js');
const K=V.key;
function flat(){const w=new V.World('systems-fixture');w.generate=function(cx,cz){const k=V.ckey(cx,cz);if(this.chunks.has(k))return this.chunks.get(k);const data=new Uint8Array(16*16*64);data.fill(12,0,256);data.fill(3,9*256,10*256);const edits=this.edits.get(k);if(edits)for(const[i,t]of edits)data[i]=t;const c={cx,cz,data,top:new Uint8Array(256).fill(9),living:true};this.chunks.set(k,c);this.dirty.add(k);return c;};return w;}
const actor={x:25,y:10,z:25};
function ticks(w,n=1,p=actor){for(let i=0;i<n;i++)V.tickSystems(w,p,4);}
function lever(w,x=0,z=0){w.set(x,10,z,43);V.toggleMachine(w,K(x,10,z));}
function container(w,x,y,z,kind,items=[]){w.set(x,y,z,kind==='chest'?21:kind==='hopper'?50:20);const k=K(x,y,z);w.entities[k]=kind==='furnace'?{kind,input:null,fuel:null,output:null,burn:0,progress:0}:{kind,slots:new V.Inventory(kind==='chest'?27:5,items).slots};return w.entities[k];}
function total(w,id){return Object.values(w.entities).reduce((n,e)=>n+(e.kind==='furnace'?[e.input,e.fuel,e.output]:e.slots).reduce((n,s)=>n+(s?.id===id?s.count:0),0),0);}

test('all 44 registered recipes have shapes with exactly their documented costs',()=>{assert.equal(V.recipes.length,44);for(const r of V.recipes){const cost={};for(const row of V.patterns[r.out])for(const id of row)if(id)cost[id]=(cost[id]||0)+1;assert.deepEqual(cost,r.cost,r.name);}});
test('2x2 workbench recipe matches and consumes exactly four planks',()=>{const slots=Array.from({length:4},()=>({id:7,count:2})),inv=new V.Inventory();assert.equal(V.craftGrid(slots,2,inv).out,19);assert.equal(inv.count(19),1);assert.ok(slots.every(s=>s.count===1));});
test('translated stick pattern is recognized',()=>{const s=Array(9).fill(null);s[5]={id:7,count:1};s[8]={id:7,count:1};assert.equal(V.matchGrid(s,3).out,100);});
test('mirrored axe pattern is recognized',()=>{const s=[7,7,0,100,7,0,100,0,0].map(id=>id?{id,count:1}:null);assert.equal(V.matchGrid(s,3).out,121);});
test('same costs in the wrong shape are rejected',()=>{const s=[7,100,7,100,7,0,0,0,0].map(id=>id?{id,count:1}:null);assert.equal(V.matchGrid(s,3),null);});
test('extra ingredients invalidate an otherwise valid recipe',()=>{assert.equal(V.matchGrid([{id:5,count:1},{id:2,count:1},null,null],2),null);});
test('3x3 recipes do not fit the hand grid',()=>{const inv=new V.Inventory();inv.add(7,3);inv.add(100,2);const s=Array(4).fill(null);assert.equal(V.fillGrid(s,2,inv,V.recipes.find(r=>r.out===120)),false);assert.equal(inv.count(7),3);});
test('craft output-full failure is atomic',()=>{const inv=new V.Inventory(1,[{id:2,count:64}]),s=[{id:5,count:1},null,null,null],before=JSON.stringify(s);assert.equal(V.craftGrid(s,2,inv),false);assert.equal(JSON.stringify(s),before);assert.equal(inv.count(2),64);});
test('loading a recipe exchanges inventory and grid without duplication',()=>{const inv=new V.Inventory();inv.add(5,3);const s=Array(4).fill(null),r=V.recipes.find(r=>r.out===7);assert.ok(V.fillGrid(s,2,inv,r));assert.equal(inv.count(5),2);assert.ok(V.fillGrid(s,2,inv,r));assert.equal(inv.count(5),2);assert.equal(s[0].count,1);});
test('unknown recipe is rejected',()=>{assert.equal(V.fillGrid([],3,new V.Inventory(),{out:7}),false);});
test('work queue deduplicates and preserves insertion order',()=>{const q=new V.WorkQueue(['a','b','a']);assert.equal(q.size,2);assert.equal(q.take(),'a');q.add('a');assert.deepEqual(q.export(),['b','a']);});
test('invalid world writes are rejected before generation',()=>{const w=flat();for(const p of[[NaN,10,0,1],[Infinity,10,0,1],[0,0,0,1],[0,10,0,999]])assert.equal(w.set(...p),false);assert.equal(w.chunks.size,0);});
test('wire attenuates 15 through 1 and stops at the sixteenth wire',()=>{const w=flat();lever(w);for(let x=1;x<=17;x++)w.set(x,10,0,41);ticks(w);for(let x=1;x<=15;x++)assert.equal(w.logic[K(x,10,0)].power,16-x);assert.equal(w.logic[K(16,10,0)].power,0);});
test('wire branches power lamps, and removal disconnects them',()=>{const w=flat();lever(w);for(let x=1;x<=4;x++)w.set(x,10,0,41);w.set(4,10,1,45);ticks(w);assert.equal(w.get(4,10,1),46);w.set(2,10,0,0);ticks(w);assert.equal(w.get(4,10,1),45);});
test('wire loops do not latch without a source',()=>{const w=flat();lever(w);for(const[x,z]of[[1,0],[2,0],[2,1],[1,1]])w.set(x,10,z,41);ticks(w);V.toggleMachine(w,K(0,10,0));ticks(w);assert.ok(Object.values(w.logic).filter(s=>s.kind==='wire').every(s=>s.power===0));});
test('negative chunk boundaries preserve signal connectivity',()=>{const w=flat();lever(w,-18);for(let x=-17;x<=-13;x++)w.set(x,10,0,41);w.set(-12,10,0,45);ticks(w);assert.equal(w.get(-12,10,0),46);});
test('repeater delays and restores the signal in its forward direction',()=>{const w=flat();lever(w);w.set(1,10,0,41);w.set(2,10,0,53);w.logic[K(2,10,0)].dir=1;w.set(3,10,0,41);w.set(4,10,0,45);ticks(w,2);assert.equal(w.get(4,10,0),45);ticks(w);assert.equal(w.get(4,10,0),46);assert.equal(w.logic[K(3,10,0)].power,15);});
test('a repeater does not receive power from its front',()=>{const w=flat();w.set(0,10,0,53);w.logic[K(0,10,0)].dir=1;lever(w,1);ticks(w,9);assert.equal(w.logic[K(0,10,0)].output,false);});
test('repeater delay cycles 1 to 4',()=>{const w=flat();w.set(0,10,0,53);for(let i=0;i<4;i++)V.toggleMachine(w,K(0,10,0));assert.equal(w.logic[K(0,10,0)].delay,2);});
test('button expires after ten simulation ticks',()=>{const w=flat();w.set(0,10,0,60);w.set(1,10,0,45);V.toggleMachine(w,K(0,10,0));ticks(w,9);assert.equal(w.get(1,10,0),46);ticks(w);assert.equal(w.get(1,10,0),45);});
test('pressure plate reacts to and releases under a player',()=>{const w=flat();w.set(0,10,0,55);w.set(1,10,0,45);ticks(w,1,{x:.5,y:10.09,z:.5});assert.equal(w.get(1,10,0),46);ticks(w);assert.equal(w.get(1,10,0),45);});
test('normal piston pushes, then retracts without pulling',()=>{const w=flat();w.set(0,10,0,47);w.logic[K(0,10,0)].dir=1;w.set(1,10,0,7);assert.ok(V.piston(w,K(0,10,0),true));assert.equal(w.get(1,10,0),49);assert.equal(w.get(2,10,0),7);assert.ok(V.piston(w,K(0,10,0),false));assert.equal(w.get(1,10,0),0);assert.equal(w.get(2,10,0),7);});
test('sticky piston retrieves one ordinary block',()=>{const w=flat();w.set(0,10,0,57);w.logic[K(0,10,0)].dir=1;w.set(1,10,0,7);V.piston(w,K(0,10,0),true);V.piston(w,K(0,10,0),false);assert.equal(w.get(1,10,0),7);assert.equal(w.get(2,10,0),0);});
test('piston push limit is twelve blocks',()=>{const w=flat();w.set(0,10,0,47);w.logic[K(0,10,0)].dir=1;for(let x=1;x<=12;x++)w.set(x,10,0,7);assert.ok(V.piston(w,K(0,10,0),true));assert.equal(w.get(13,10,0),7);});
test('thirteenth block blocks a piston atomically',()=>{const w=flat();w.set(0,10,0,47);w.logic[K(0,10,0)].dir=1;for(let x=1;x<=13;x++)w.set(x,10,0,7);const before=JSON.stringify(w.export().edits);assert.equal(V.piston(w,K(0,10,0),true),false);assert.equal(JSON.stringify(w.export().edits),before);});
test('pistons cannot move storage or overwrite a player',()=>{const w=flat();w.set(0,10,0,47);w.logic[K(0,10,0)].dir=1;w.set(1,10,0,21);assert.equal(V.piston(w,K(0,10,0),true),false);w.set(1,10,0,0);assert.equal(V.piston(w,K(0,10,0),true,[{x:1.5,y:10,z:.5}]),false);});
test('piston responds to lever switching without duplicating pushed blocks',()=>{const w=flat();w.set(0,10,0,57);w.logic[K(0,10,0)].dir=1;w.set(1,10,0,8);lever(w,0,-1);ticks(w);assert.equal(w.get(2,10,0),8);V.toggleMachine(w,K(0,10,-1));ticks(w);assert.equal(w.get(1,10,0),8);assert.equal(w.get(2,10,0),0);});
test('hopper conserves items across chest transfer',()=>{const w=flat();container(w,0,12,0,'chest',[{id:7,count:16}]);container(w,0,11,0,'hopper');container(w,0,10,0,'chest');ticks(w,100);assert.equal(total(w,7),16);assert.equal(w.entities[K(0,10,0)].slots[0].count,16);});
test('powered hopper stays locked',()=>{const w=flat();container(w,0,12,0,'chest',[{id:7,count:16}]);container(w,0,11,0,'hopper');container(w,0,10,0,'chest');w.set(1,11,0,43);V.toggleMachine(w,K(1,11,0));ticks(w,24);assert.equal(w.entities[K(0,12,0)].slots[0].count,16);});
test('blocked hopper never discards items',()=>{const w=flat();const top=container(w,0,11,0,'hopper',[{id:7,count:4}]);container(w,0,10,0,'chest',Array.from({length:27},()=>({id:2,count:64})));ticks(w,12);assert.equal(top.slots[0].count,4);});
test('hopper feeds furnace input and fuel and extracts only output',()=>{const w=flat();container(w,0,14,0,'chest',[{id:102,count:2},{id:101,count:1}]);container(w,0,13,0,'hopper');const f=container(w,0,12,0,'furnace');container(w,0,11,0,'hopper');container(w,0,10,0,'chest');for(let i=0;i<200;i++){ticks(w);V.smelt(f,.1);}assert.equal(total(w,105),2);assert.equal(total(w,102),0);assert.equal(w.entities[K(0,10,0)].slots[0].id,105);});
test('water spreads seven cells along a floor and no further',()=>{const w=flat();w.set(0,10,0,13);ticks(w,100);assert.equal(w.get(7,10,0),51);assert.equal(w.get(8,10,0),0);assert.equal(w.flows[K(7,10,0)].level,7);});
test('water falls before spreading and respects solid walls',()=>{const w=flat();w.set(0,14,0,13);w.set(1,10,0,3);ticks(w,120);assert.equal(w.get(0,10,0),51);assert.equal(w.get(1,10,0),3);assert.equal(w.get(1,13,0),0);});
test('water drains after removal of its last source',()=>{const w=flat();w.set(0,10,0,13);ticks(w,100);w.set(0,10,0,0);ticks(w,220);assert.equal(Object.keys(w.flows).length,0);});
test('lava has a three-cell lateral reach',()=>{const w=flat();w.set(0,10,0,31);ticks(w,150);assert.equal(w.get(3,10,0),52);assert.equal(w.get(4,10,0),0);});
test('water contact hardens a lava source into obsidian',()=>{const w=flat();w.set(0,10,0,31);w.set(1,10,0,13);ticks(w,20);assert.equal(w.get(0,10,0),33);});
test('flow state, queued work and machine settings survive export/import',()=>{const w=flat();w.set(-16,10,-1,13);w.set(0,10,0,53);w.logic[K(0,10,0)].dir=3;w.logic[K(0,10,0)].delay=4;ticks(w,25);const data=JSON.parse(JSON.stringify(w.export())),copy=flat();copy.import(data);assert.deepEqual(copy.flows,w.flows);assert.equal(copy.logic[K(0,10,0)].dir,3);assert.equal(copy.logic[K(0,10,0)].delay,4);assert.equal(copy.simTick,w.simTick);});
test('hopper storage survives export/import',()=>{const w=flat();container(w,0,10,0,'hopper',[{id:105,count:12}]);const copy=flat();copy.import(JSON.parse(JSON.stringify(w.export())));assert.equal(copy.entities[K(0,10,0)].slots[0].count,12);assert.equal(copy.entities[K(0,10,0)].slots.length,5);});
test('legacy 2.0 world data acquires empty simulation state',()=>{const copy=flat();copy.import({edits:[],entities:{},crops:{}});assert.equal(copy.updates.size,0);assert.deepEqual(copy.logic,{});});
test('malformed queue and out-of-bounds fluid levels are rejected',()=>{for(const data of[{edits:[],updates:['bad']},{edits:[],flows:{'0,10,0':{kind:13,level:8}}}])assert.throws(()=>flat().import(data));});
test('fluid evolution is deterministic for the same edits and tick schedule',()=>{const a=flat(),b=flat();for(const w of[a,b]){w.set(-1,13,-1,13);w.set(2,10,0,31);ticks(w,70);}assert.deepEqual(a.export(),b.export());});
test('chunk eviction retains wire states and fluid edits',()=>{const w=flat();lever(w,-17);w.set(-16,10,0,41);ticks(w);w.chunks.clear();assert.equal(w.get(-16,10,0),42);assert.equal(w.logic[K(-16,10,0)].power,15);});
test('failed semantic fluid import rolls back all world state',()=>{const w=flat();w.set(0,10,0,7);const before=JSON.stringify(w.export());const bad=flat();bad.set(0,10,0,51);const data=bad.export();data.flows={'0,10,0':{kind:31,level:1}};assert.throws(()=>w.import(data));assert.equal(JSON.stringify(w.export()),before);});
test('both ends of a pending repeater transition persist across reload',()=>{const w=flat();lever(w);w.set(1,10,0,41);w.set(2,10,0,53);w.logic[K(2,10,0)].dir=1;w.set(3,10,0,45);ticks(w);const copy=flat();copy.import(JSON.parse(JSON.stringify(w.export())));ticks(copy,2);assert.equal(copy.get(3,10,0),46);});
test('completed fluid solver reaches a stable empty work queue',()=>{const w=flat();w.set(0,10,0,13);ticks(w,400);assert.equal(w.updates.size,0);const before=JSON.stringify(w.export().edits);ticks(w,1000);assert.equal(JSON.stringify(w.export().edits),before);});
